### ISSUE TITLE
Scans limit

### ISSUE THREAD

**Issue by jevgenyonegin** [drygdryg/wigle_companion#1]
Wigle_companion scans intermittently, 4 times every two minutes, like many wi-fi scanners on Android 9+ ...wigle itself (same as oneshot) scans the network without a limit and no need wi-fi reactivation.

**Comment by drygdryg** [comment]
This project doesn't use the Android API for network scanning.
You can use it in two ways:
1. As a companion to another app that actively scans networks (for example, WiGLE Wardriving).
2. As a stand-alone scanner that requests scanning via nl80211: just add `-m real` to command line arguments.
If the WiGLE app is restricted by the Android API, you can use this tool as stand-alone scanner.

**Comment by jevgenyonegin** [comment]
Ok, it's working as stand-alone scanner, but only with screen on option, termux wake lock doesn't help:( It is not so easy to keep phone in the pocket with activated screen:)

**Comment by drygdryg** [comment]
Perhaps this app will help you avoid sleeping Wi-Fi and CPU: https://github.com/d4rken/wakelock-revamp/releases

**Comment by jevgenyonegin** [comment]
Everything turned out to be easier than I thought. it was necessary to turn off the wi-fi switch and location on, as in the oneshot. Now termux wakelock started working as it should! now I can take a walk;)

**Comment by drygdryg** [comment]
Have a nice walk!
