### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by eda-abec** [drygdryg/wigle_companion#3]
Not sure what to use it for now, but just could be there...

**Comment by drygdryg** [comment]
I have implemented it, test it and leave feedback: https://github.com/drygdryg/wigle_companion/tree/last_seen_memorization
Before starting, you need to make a migration (add a column to the table). You can do this from the sqlite console. For Termux, the actions are as follows:
```
pkg install sqlite
cd wigle_companion/
sqlite3 networks.db "ALTER TABLE network ADD COLUMN last_seen TIMESTAMP"
```
After that, run `main.py` as usual.

**Comment by eda-abec** [comment]
Thanks, at first look it looks fine, I'll test it for a few days.

**Comment by eda-abec** [comment]
It's working without problems, you can merge it :)
